plugins:
  - prettier-plugin-java
overrides:
  - files:
      - "*.java"
    options:
      printWidth: 120
      tabWidth: 2
      useTabs: false
      trailingComma: "none"
      bracketSpacing: true
      bracketSameLine: false
      endOfLine: lf