modLoader="javafml"
loaderVersion="[40,)"

license="MIT"

[[mods]]
modId="waste"
version="${file.jarVersion}"
displayName="Waste"
description='''
This mod allows players to manage and recycle waste materials in Minecraft.
'''

# Forge dependency
[[dependencies.waste]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

# Minecraft dependency
[[dependencies.waste]]
modId="minecraft"
mandatory=true
versionRange="${mc_version_range}"
ordering="NONE"
side="BOTH"

# Just Enough Items (JEI) dependency
[[dependencies.waste]]
modId="jei"
mandatory=false
versionRange="${jei_version_range}"
ordering="NONE"
side="CLIENT"
[[dependencies.waste]]
modId="terrablender"
mandatory=true
versionRange="${terrablender_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.waste]]
modId="lostcities"
mandatory=true
versionRange="[1.18-5.3.29,)"
ordering="AFTER"
side="BOTH"